### ISSUE TITLE
Chromium notification issues.

### ISSUE THREAD

**Issue by rilian-la-te** [equeim/xfce4-snw-plugin#6]
After removal a Chromium notification item, zombie SNItem exists in plugin.

**Comment by equeim** [comment]
How to enable statusnotifier in chromium?

**Comment by rilian-la-te** [comment]
XDG_CURRENT_DESKTOP=Unity chromium

**Comment by equeim** [comment]
I don't see any icon. Chromium creates only dbusmenu interface.
I'm using the latest Chromium from Arch repos.

**Comment by rilian-la-te** [comment]
Install this extension: Checker Plus for Gmail™
And use notification test. You will see icons and bug.

**Comment by rilian-la-te** [comment]
OK, but snitem is perfectly correct without title. Pinging ID is mor spec conforming, I think:-)
